[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_ADMIN_PASSWORD = "pdx@dm1n!!"
  VITE_SUPABASE_URL = "your_supabase_url_here"
  VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
